id: P81811D3A
initial_creation_type: input
source_metadata:
  title: Tārānamaskāraikaviṃśatistotra
  language: zh
  volumes:
    3508fa7a53104e8fac448114175eb6e3:
      title: .txt
      base_file: .txt.txt
      work_id: W5B6C8074
  chapter_to_tile: {}
created_at: '2022-03-01T23:40:25.640552'
last_modified_at: '2022-03-01T23:40:25.640562'
